# Kubernetes Cluster Inventory
# Generated by Terraform

[k8s_control_plane]
%{ for cp in control_nodes ~}
${cp.name} ansible_host=${cp.ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
%{ endfor ~}

[k8s_workers]
%{ for worker in worker_nodes ~}
${worker.name} ansible_host=${worker.ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
%{ endfor ~}

[k8s_cluster:children]
k8s_control_plane
k8s_workers

[k8s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
