---
- name: Setup Kubernetes Worker Nodes
  hosts: k8s_workers
  become: yes
  gather_facts: false
  
  tasks:
    - name: Read join command from file
      slurp:
        src: /tmp/k8s_join_command.sh
      register: join_command_file
      delegate_to: localhost
      run_once: true
      become: no

    - name: Set join command fact
      set_fact:
        join_command: "{{ join_command_file.content | b64decode | trim }}"

    - name: Join worker node to cluster
      shell: "{{ join_command }}"
      become: yes
      register: join_result

    - name: Display join result
      debug:
        var: join_result.stdout_lines

    - name: Wait for node to be ready
      pause:
        seconds: 30

- name: Verify worker nodes joined
  hosts: k8s_control_plane
  become_user: ubuntu
  gather_facts: false
  
  tasks:
    - name: Get nodes status
      shell: kubectl get nodes -o wide
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
      register: nodes_status

    - name: Display nodes status
      debug:
        var: nodes_status.stdout_lines
